### PR TITLE
Jbusecke xesmf xgcm

### PR DESCRIPTION
**Pull request by jbusecke**
Hi @rabernat, this is a first draft of the lecture. Using xesmf with the conservative method required quite a bit of 'massaging'. I think this is probably already a lot of material? I can add some xgcm examples as well if you think that fits.

The intro will have to be adjusted depending on if I do include that or not. Also I still need to write the conclusions and clean the whole notebook up. Let me know what you think.

### CODE REVIEW

**Comment by rabernat** [comment]
Could you please remove all files but your new notebook from the PR?

**Comment by jbusecke** [comment]
I cleaned the notebook up, added some more detailed explanations (about cases in which conservative regridding is more appropriate) and added an example of how to calculate the merdional SST gradient in SOSE using xgcm. I also added a video in the introduction...not sure how well that plays with the book...is there a way to preview the final book version for a PR? 

I also think I would need some guidance where to 'plug' in the lecture appropriately.

**Comment by rabernat** [comment]
Great!

Could you just update the table of contents? Duplicate this entry:
https://github.com/earth-env-data-science/earth-env-data-science-book/blob/0e87140a7728a59f195b375e174e495c3b694afb/_data/toc.yml#L113-L118

(Skip the assignment part)

**Comment by jbusecke** [comment]
I added a TOC entry and slightly modified the title. The additional files are removed.

**Comment by rabernat** [comment]
Awesome!

**Comment by rabernat** [comment]
You can follow the build here https://circleci.com/gh/earth-env-data-science/earth-env-data-science-book

**Comment by jbusecke** [comment]
It seems like the book doesnt like the video...trying to fix that in a different PR #4.

**Pull request merged**
