### PR TITLE
Update Assignment 3 Header

### PR DESCRIPTION
**Pull request by jtcimba**
Reformatted to match other Assignment headers

### CODE REVIEW

**Comment by rabernat** [comment]
Thank you!

**Comment by jtcimba** [comment]
No problem! I also noticed that some of the assignments are numbered (3 and 4) while others are not. Let me know if you prefer them to be formatted one way or the other.

**Comment by rabernat** [comment]
I would prefer to remove all the numbering from the titles.

Also, it looks like the build is failing. It seems very similar to this issue, and probably has the same solution:
- https://github.com/pangeo-forge/pangeo-forge-recipes/pull/332

**Comment by rabernat** [comment]
Amazing, thank you!

**Pull request merged**
