### PR TITLE
Add Tim Crone to author list

### PR DESCRIPTION
**Pull request by tjcrone**
Also testing Actions.

### CODE REVIEW

**Comment by rabernat** [comment]
Looks like you found a typo in the requirements.txt. I always do that!

**Comment by tjcrone** [comment]
Yeah no worries. I fixed it. Do we want to try to fix all of those header level issues? If you don't want to fix them, it might be nice to turn off those particular warnings so it is easier to spot other issues. I don't know if that is a build option.

**Comment by rabernat** [comment]
I think our goal should be to eventually make everything super clean and warning free. But we don't have to do it all at once.

**Comment by rabernat** [comment]
Author info should also go here:

https://github.com/earth-env-data-science/earth-env-data-science-book/blob/master/src/_config.yml#L20

**Comment by tjcrone** [comment]
Okay I will fix authorship in _config.yml in a separate PR. For now, let's merge this and see if the site shows up correctly. Also, it is not obvious to me that this Jekyll config is fully compliant with the new format. Is Jekyll used under-the-hood or something else? If something else, we may also be able to remove the Jekyll-related scripts in https://github.com/earth-env-data-science/earth-env-data-science-book/tree/master/scripts.

**Comment by rabernat** [comment]
We can remove everything jekyll related. It's not longer used in this version of jupyter-book.

**Comment by tjcrone** [comment]
Okay should we merge this since it seems to build fine locally and mostly work, or continue working on _config.yml etc. so that the site is perfect before it goes live?

**Pull request merged**
